version: '3.6'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        authors: "jhwinter"
        maintainer: "jhwinter"
      args:
        DEBIAN_FRONTEND: noninteractive
        TZ: "America/New_York"
    image: splyse:nep5-faucet
    container_name: nep5-faucet
    working_dir: /app/
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - "chains-volume:/root/.neopython/Chains"
    network_mode: bridge
volumes:
  chains-volume:
